server:
  port: 8888


spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: sem8_aop
          uri: http://localhost:8082/
          predicates:
            - Path=/shop/**
        - id: sem5_jpa
          uri: http://localhost:8081/
          predicates:
            - Path=/tasks/**